### ISSUE TITLE
update 1.10.2 please!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by 963548217** [TheLarsinator/LotsOMobs#12]
why stop update?
without this mod I really can not play Minecraft
edit:so please update 1.10.2

**Comment by PitchBright** [comment]
This is not what GitHub "ISSUE" reports is for. Please close this.

**Comment by 963548217** [comment]
but the mod is dead.

**Comment by PitchBright** [comment]
GitHub issue tracker is for people who need to report a technical issue with the project. Close the issue, stop abusing the platform, or you'll be reported. It's that simple.

**Comment by mgdgfbhevdyeh** [comment]
@963548217 我就是在twitter上問TheLarsinator為什麼不更新1.10.2的lngzhang
既然MOD已經棄坑，就去玩別的MOD去吧
我知道你是華人

**Comment by mgdgfbhevdyeh** [comment]
please close this @963548217

**Comment by 963548217** [comment]
#12 closed

**Comment by 963548217** [comment]
#12 closed

**Comment by mgdgfbhevdyeh** [comment]
You will not shut down issues?

**Comment by mgdgfbhevdyeh** [comment]
kid?LOLOLOLOLOL

**Comment by 963548217** [comment]
@mgdgfbhevdyeh roll!

**Comment by TheLarsinator** [comment]
If you want to know something, send me an email or a tweet. Dont use the issue tracker
