### ISSUE TITLE
Salt Bath doesn't require additional salt after each use

### ISSUE THREAD

**Issue by PitchBright** [TheLarsinator/LotsOMobs#7]
Salt Bath doesn't require additional salt after each use.

**Comment by TheLarsinator** [comment]
This problem has been fixed :D

**Comment by PitchBright** [comment]
For Re-open.

The Salt Bath is pretty wonky, sometimes it adds salt back to my inventory… sometimes it takes it and uses up a Hide and Spits the Salted Hide out without using up the Salt. Sometimes it uses the salt up without spitting out a Salted Hide. It always takes 2 Salts
